package com.eafc26.discordstats.config

enum class PhraseCategory(val key: String, val displayName: String, val defaults: List<String>) {

    RATING(
        key = "rating",
        displayName = "Comentário de nota (Bagre)",
        defaults = listOf(
            "Nem o algoritmo conseguiu defender essa atuação.",
            "Hoje a nota chegou antes das desculpas.",
            "Foi uma atuação... memorável. Pelo motivo errado.",
            "O videogame tentou ajudar, mas desistiu.",
            "Hoje o futebol passou longe.",
            "A partida foi longa. A nota também sentiu.",
            "Não foi o pior jogo da história. Ficou perto.",
            "O técnico já está pensando em alternativas.",
            "Hoje jogou no modo difícil... para o próprio time.",
            "A torcida aplaudiu o final do jogo.",
            "Deixou tudo no vestiário. Pena que era o uniforme.",
            "Contribuiu com presença. A partida pediu mais.",
            "Estava em campo. Isso ninguém tira.",
            "Hoje fez o adversário parecer muito bom.",
            "A nota reflete com precisão o que aconteceu.",
            "Talvez a próxima partida seja diferente. Talvez.",
            "Foi uma lição. Dolorosa, mas uma lição.",
            "O campo estava difícil. A nota estava honesta.",
            "Dia de recarregar as energias.",
            "O mais importante é ter jogado. O segundo é não repetir.",
        ),
    ),

    PASS(
        key = "pass",
        displayName = "Passes errados (Bagre)",
        defaults = listOf(
            "Distribuiu o jogo... para os dois times.",
            "Hoje enxergou todo mundo com a mesma camisa.",
            "Acertou o GPS... do adversário.",
            "Treinou lançamento para o outro time.",
            "Transformou posse de bola em doação.",
            "Cada passe uma surpresa. Nem sempre boa.",
            "O adversário aproveitou cada presente.",
            "Criou chances. Para os dois lados.",
            "A bola saiu. Não pelo caminho esperado.",
            "Fez o adversário se sentir em casa.",
            "Decidiu compartilhar a bola com generosidade.",
            "O campo tinha dois times. A bola visitou os dois.",
            "Hoje o passe virou obra de arte abstrata.",
            "Contribuiu para a posse... adversária.",
            "Cada erro foi uma oportunidade. Para o outro lado.",
            "A bola encontrou o adversário antes do companheiro.",
            "Passou a bola com confiança. Para o lado errado.",
            "Ajudou a manter o jogo movimentado. Dos dois lados.",
            "O adversário ficou grato pela contribuição.",
            "Hoje o passe foi uma caixinha de surpresas.",
        ),
    ),

    TACKLE(
        key = "tackle",
        displayName = "Desarmes (Bagre)",
        defaults = listOf(
            "Chegou em todas. Na bola, em quase nenhuma.",
            "Foi firme... contra o vento.",
            "Marcou presença. O adversário agradeceu.",
            "Foi para o combate sem combinar com a bola.",
            "Entrou em todos os carrinhos... atrasado.",
            "Tentou. Isso ninguém pode negar.",
            "O adversário passou. E agradeceu a passagem.",
            "Força não faltou. Precisão ficou de fora.",
            "Hoje a marcação foi mais decorativa.",
            "Mostrou disposição. A bola não correspondeu.",
            "Estava em todos os duelos. Saiu de poucos.",
            "Correu atrás da bola o jogo inteiro. Ela foi mais rápida.",
            "A intenção era boa. O resultado foi outra história.",
            "Hoje o adversário teve campo livre. Com direito a escolta.",
            "Tentou fechar os espaços. Os espaços venceram.",
            "Brigou com a bola. A bola ganhou.",
            "Deu trabalho para o adversário... entrar em campo.",
            "Hoje a marcação foi mais sugestão do que realidade.",
            "O rival passou sem maiores dificuldades. Ele viu de perto.",
            "Defendeu com o coração. A técnica foi de férias.",
        ),
    ),

    SHOOTING(
        key = "shooting",
        displayName = "Chutes (Bagre)",
        defaults = listOf(
            "Levou perigo... para a arquibancada.",
            "O goleiro terminou o jogo sem sujar o uniforme.",
            "O gol entrou em modo invisível.",
            "A pontaria pediu folga.",
            "Mudou a decoração atrás da goleira.",
            "Finalizou. A bola foi visitar outros destinos.",
            "O gol estava lá. Só não onde ele chutou.",
            "Tentou achar o ângulo. O ângulo não estava em casa.",
            "Chutou com convicção. O resultado ficou em dívida.",
            "A goleira agradeceu por não ter trabalhado.",
            "Forçou o placar a não mudar.",
            "Hoje o gol estava em reforma.",
            "A bola foi longe. Bem longe.",
            "Mostrou que a trave é mesmo redonda.",
            "O goleiro rival teve uma noite tranquila.",
            "Finalizou em dose dupla. Acertou em dose zero.",
            "Hoje o gol estava com cartão cheio.",
            "Cada finalização foi uma história. Sem final feliz.",
            "O adversário agradeceu cada chute para fora.",
            "A bola e a meta tiveram opiniões diferentes.",
        ),
    ),

    MVP(
        key = "mvp",
        displayName = "Craque da Partida (MVP)",
        defaults = listOf(
            "Hoje jogou de terno.",
            "Parecia que sabia o roteiro da partida.",
            "Quando o time precisou, apareceu.",
            "Craque dentro e fora das estatísticas.",
            "Hoje fez parecer fácil.",
            "Colocou o time nas costas.",
            "The controller understood the assignment.",
            "Hoje o futebol sorriu para ele.",
            "Fez o que precisava ser feito, quando precisava.",
            "Diferença entre tentar e conseguir? Ele mostrou.",
            "Hoje foi o dono do campo.",
            "O adversário tentou, mas não encontrou resposta.",
            "Quando a pressão aumentou, ele cresceu junto.",
            "Cada toque tinha intenção. Cada intenção tinha resultado.",
            "Hoje a partida passou pelas suas mãos.",
            "Transformou dificuldade em oportunidade.",
            "O time jogou bem. Ele jogou melhor.",
            "Hoje a diferença tinha nome.",
            "Fez o adversário pensar duas vezes. Depois três.",
            "Jogou como se não houvesse segunda chance. Não precisou.",
            "Hoje ele foi o manual de como se joga futebol.",
            "Lembrou a todos por que é craque.",
        ),
    ),

    XERIFE(
        key = "xerife",
        displayName = "Xerife (melhor defensor)",
        defaults = listOf(
            "Hoje ninguém passou sem autorização.",
            "Fechou a porta e jogou a chave fora.",
            "O adversário ainda procura espaço.",
            "Cobrou pedágio em cada ataque.",
            "Hoje mandou na defesa.",
            "Cada carrinho, uma sentença.",
            "O rival tentou. Ele não deixou.",
            "Hoje foi o seguro do time.",
            "Brigou por cada centímetro com sucesso.",
            "Onde estava, o adversário não passou.",
            "Foi o controlador de tráfego da defesa.",
            "Hoje a marcação foi cirúrgica.",
            "Nenhum ataque passou sem pagar o preço.",
            "A defesa tinha um nome: ele.",
            "O adversário mudou de rota. Ele mudou junto.",
            "Hoje a bola voltou mais do que avançou.",
            "Fez a marcação parecer arte.",
            "Cada duelo era uma batalha. Ele venceu a guerra.",
            "Hoje o meio-campo adversário foi turismo.",
            "A defesa agradeceu a presença.",
            "Fechou os espaços como se soubesse o que estava vindo.",
            "Hoje ele foi o seguro do time. Sem franquia.",
        ),
    ),

    GOALKEEPER(
        key = "goalkeeper",
        displayName = "Muralha (goleiro)",
        defaults = listOf(
            "Hoje fechou o gol.",
            "Quando precisou aparecer, apareceu.",
            "Nem GPS encontrou espaço.",
            "A última palavra quase sempre foi dele.",
            "Foi buscar até o que parecia perdido.",
            "Hoje a luva trabalhou em hora extra.",
            "O placar deveria ter sido pior. Ele não deixou.",
            "Cada defesa, uma afirmação.",
            "Hoje o gol ficou sob custódia.",
            "Os chutes vieram. Ele devolveu.",
            "Fez o adversário acreditar que era difícil marcar. Era.",
            "Hoje ele foi o plano B, C e D do time.",
            "Quando a defesa falhou, ele não falhou.",
            "O gol ficou em boas mãos. Literalmente.",
            "Hoje o goleiro foi o melhor jogador do campo.",
            "Segurou o que tinha que segurar e mais um pouco.",
            "O adversário chutou muito. Entrou pouco.",
            "Hoje foi difícil fazer gol. Por causa dele.",
            "A trave e ele foram parceiros hoje.",
            "Partida difícil. Saída fácil: defensiva e segura.",
        ),
    ),
}
