package com.eafc26.discordstats.config

enum class PhraseCategory(val key: String, val displayName: String, val defaults: List<String>) {

    RATING(
        key = "rating",
        displayName = "Comentário de nota (Bagre)",
        defaults = listOf(
            // Sarcastic/funny Bagre phrases
            "Marcou presença. Futebol ficou para outro dia.",
            "Foi guerreiro. Só esqueceu a técnica.",
            "A bola pediu arrego.",
            "Entrou em campo e saiu da partida.",
            "Hoje brigou mais com a bola do que com o adversário.",
            "O GPS da chuteira estava recalculando a rota.",
            "Tentou ajudar. Não ficou claro quem.",
            "Se esforço fosse gol, fazia três.",
            "Nem o algoritmo conseguiu defender essa atuação.",
            "Hoje a nota chegou antes das desculpas.",
            "Foi uma atuação... memorável. Pelo motivo errado.",
            "O videogame tentou ajudar, mas desistiu.",
            "Hoje o futebol passou longe.",
            "A partida foi longa. A nota também sentiu.",
            "Não foi o pior jogo da história. Ficou perto.",
            "O técnico já está pensando em alternativas.",
            "Hoje jogou no modo difícil... para o próprio time.",
            "A torcida aplaudiu o final do jogo.",
            "Deixou tudo no vestiário. Pena que era o uniforme.",
            "Estava em campo. Isso ninguém tira.",
            "Hoje fez o adversário parecer muito bom.",
            "A nota reflete com precisão o que aconteceu.",
            "Talvez a próxima partida seja diferente. Talvez.",
            "Foi uma lição. Dolorosa, mas uma lição.",
            "O campo estava difícil. A nota estava honesta.",
            "Dia de recarregar as energias.",
            "O mais importante é ter jogado. O segundo é não repetir.",
            "Se a intenção valesse ponto, sairia com nota 10.",
            "Participou. Da forma como não deveria.",
            "O adversário mandou um cartão de agradecimento.",
            "Hoje o time jogou com um a menos. Mesmo com ele em campo.",
            "Fez o impossível: ajudou e atrapalhou ao mesmo tempo.",
            "Correu muito. Só faltou direção.",
            "Trabalho duro. Resultado suave.",
            "Deu o sangue. Só não deu a técnica.",
        ),
    ),

    PASS(
        key = "pass",
        displayName = "Passes errados (Bagre)",
        defaults = listOf(
            "Distribuiu o jogo... para os dois times.",
            "Hoje enxergou todo mundo com a mesma camisa.",
            "Acertou o GPS... do adversário.",
            "Treinou lançamento para o outro time.",
            "Transformou posse de bola em doação.",
            "Cada passe uma surpresa. Nem sempre boa.",
            "O adversário aproveitou cada presente.",
            "Criou chances. Para os dois lados.",
            "A bola saiu. Não pelo caminho esperado.",
            "Fez o adversário se sentir em casa.",
            "Decidiu compartilhar a bola com generosidade.",
            "O campo tinha dois times. A bola visitou os dois.",
            "Hoje o passe virou obra de arte abstrata.",
            "Contribuiu para a posse... adversária.",
            "Cada erro foi uma oportunidade. Para o outro lado.",
            "A bola encontrou o adversário antes do companheiro.",
            "Passou a bola com confiança. Para o lado errado.",
            "Ajudou a manter o jogo movimentado. Dos dois lados.",
            "O adversário ficou grato pela contribuição.",
            "Hoje o passe foi uma caixinha de surpresas.",
            "Jogou no modo aleatório. A bola também.",
            "O mapa tático dele era outro.",
            "Tentou um passe de gênio. Saiu um presente de grego.",
            "Passou mais bola pro rival do que pro companheiro.",
        ),
    ),

    TACKLE(
        key = "tackle",
        displayName = "Desarmes (Bagre)",
        defaults = listOf(
            "Chegou em todas. Na bola, em quase nenhuma.",
            "Foi firme... contra o vento.",
            "Marcou presença. O adversário agradeceu.",
            "Foi para o combate sem combinar com a bola.",
            "Entrou em todos os carrinhos... atrasado.",
            "Tentou. Isso ninguém pode negar.",
            "O adversário passou. E agradeceu a passagem.",
            "Força não faltou. Precisão ficou de fora.",
            "Hoje a marcação foi mais decorativa.",
            "Mostrou disposição. A bola não correspondeu.",
            "Estava em todos os duelos. Saiu de poucos.",
            "Correu atrás da bola o jogo inteiro. Ela foi mais rápida.",
            "A intenção era boa. O resultado foi outra história.",
            "Hoje o adversário teve campo livre. Com direito a escolta.",
            "Tentou fechar os espaços. Os espaços venceram.",
            "Brigou com a bola. A bola ganhou.",
            "Deu trabalho para o adversário... entrar em campo.",
            "Hoje a marcação foi mais sugestão do que realidade.",
            "O rival passou sem maiores dificuldades. Ele viu de perto.",
            "Defendeu com o coração. A técnica foi de férias.",
            "Pulou em cima de tudo. Menos da bola.",
            "Quis marcar forte. Marcou errado.",
            "Dava medo ao adversário. De tanto espaço.",
        ),
    ),

    SHOOTING(
        key = "shooting",
        displayName = "Chutes (Bagre)",
        defaults = listOf(
            "Levou perigo... para a arquibancada.",
            "O goleiro terminou o jogo sem sujar o uniforme.",
            "O gol entrou em modo invisível.",
            "A pontaria pediu folga.",
            "Mudou a decoração atrás da goleira.",
            "Finalizou. A bola foi visitar outros destinos.",
            "O gol estava lá. Só não onde ele chutou.",
            "Tentou achar o ângulo. O ângulo não estava em casa.",
            "Chutou com convicção. O resultado ficou em dívida.",
            "A goleira agradeceu por não ter trabalhado.",
            "Forçou o placar a não mudar.",
            "Hoje o gol estava em reforma.",
            "A bola foi longe. Bem longe.",
            "Mostrou que a trave é mesmo redonda.",
            "O goleiro rival teve uma noite tranquila.",
            "Finalizou em dose dupla. Acertou em dose zero.",
            "Hoje o gol estava com cartão cheio.",
            "Cada finalização foi uma história. Sem final feliz.",
            "O adversário agradeceu cada chute para fora.",
            "A bola e a meta tiveram opiniões diferentes.",
            "Tentou de tudo. Menos acertar o gol.",
            "O gol estava sempre um metro para o lado.",
        ),
    ),

    MVP(
        key = "mvp",
        displayName = "Craque da Partida (MVP)",
        defaults = listOf(
            // Personality-filled MVP phrases
            "Chamou a responsabilidade.",
            "Jogou de terno.",
            "Levou o piano sozinho.",
            "Hoje parecia jogar outro esporte.",
            "Quando a bola queimava, ela procurava ele.",
            "A defesa vai sonhar com ele.",
            "Fez parecer fácil.",
            "Craque decide. Hoje decidiu.",
            "Parecia que sabia o roteiro da partida.",
            "Quando o time precisou, apareceu.",
            "Craque dentro e fora das estatísticas.",
            "Colocou o time nas costas.",
            "Hoje o controle estava obedecendo.",
            "Hoje o futebol sorriu para ele.",
            "Fez o que precisava ser feito, quando precisava.",
            "Diferença entre tentar e conseguir? Ele mostrou.",
            "Hoje foi o dono do campo.",
            "O adversário tentou, mas não encontrou resposta.",
            "Quando a pressão aumentou, ele cresceu junto.",
            "Cada toque tinha intenção. Cada intenção tinha resultado.",
            "Hoje a partida passou pelas suas mãos.",
            "Transformou dificuldade em oportunidade.",
            "O time jogou bem. Ele jogou melhor.",
            "Hoje a diferença tinha nome.",
            "Fez o adversário pensar duas vezes. Depois três.",
            "Jogou como se não houvesse segunda chance. Não precisou.",
            "Hoje ele foi o manual de como se joga futebol.",
            "Lembrou a todos por que é craque.",
            "Vestiu a camisa e mostrou o que é protagonismo.",
            "O jogo girou em torno dele. E ele girou em torno do gol.",
            "Quem olhou viu. Quem viu aplaudiu.",
            "Não deu chance ao azar. Criou todas as próprias.",
            "O time precisava de um herói. Ele se candidatou.",
            "Fez a diferença quando ela era necessária.",
            "Transformou pressão em combustível.",
            "Se era para brilhar, brilhou.",
        ),
    ),

    XERIFE(
        key = "xerife",
        displayName = "Xerife (melhor defensor)",
        defaults = listOf(
            // Defensive personality phrases
            "Hoje ninguém passou em paz.",
            "Fechou a porta.",
            "Virou muro.",
            "Autorização negada.",
            "Resolveu tudo na base da dividida.",
            "Quem entrou encontrou pedágio.",
            "Fechou a porta e jogou a chave fora.",
            "O adversário ainda procura espaço.",
            "Cobrou pedágio em cada ataque.",
            "Hoje mandou na defesa.",
            "Cada carrinho, uma sentença.",
            "O rival tentou. Ele não deixou.",
            "Hoje foi o seguro do time.",
            "Brigou por cada centímetro com sucesso.",
            "Onde estava, o adversário não passou.",
            "Foi o controlador de tráfego da defesa.",
            "Hoje a marcação foi cirúrgica.",
            "Nenhum ataque passou sem pagar o preço.",
            "A defesa tinha um nome: ele.",
            "O adversário mudou de rota. Ele mudou junto.",
            "Hoje a bola voltou mais do que avançou.",
            "Fez a marcação parecer arte.",
            "Cada duelo era uma batalha. Ele venceu a guerra.",
            "Hoje o meio-campo adversário foi turismo.",
            "A defesa agradeceu a presença.",
            "Fechou os espaços como se soubesse o que estava vindo.",
            "Hoje ele foi o seguro do time. Sem franquia.",
            "Hoje a defesa tinha dono.",
            "Quem tentou passar, voltou.",
            "Fez questão de complicar a vida do atacante.",
            "Botou ordem no setor.",
            "Foi muralha ambulante.",
        ),
    ),

    GOALKEEPER(
        key = "goalkeeper",
        displayName = "Muralha (goleiro)",
        defaults = listOf(
            "Hoje fechou o gol.",
            "Quando precisou aparecer, apareceu.",
            "Nem GPS encontrou espaço.",
            "A última palavra quase sempre foi dele.",
            "Foi buscar até o que parecia perdido.",
            "Hoje a luva trabalhou em hora extra.",
            "O placar deveria ter sido pior. Ele não deixou.",
            "Cada defesa, uma afirmação.",
            "Hoje o gol ficou sob custódia.",
            "Os chutes vieram. Ele devolveu.",
            "Fez o adversário acreditar que era difícil marcar. Era.",
            "Hoje ele foi o plano B, C e D do time.",
            "Quando a defesa falhou, ele não falhou.",
            "O gol ficou em boas mãos. Literalmente.",
            "Hoje o goleiro foi o melhor jogador do campo.",
            "Segurou o que tinha que segurar e mais um pouco.",
            "O adversário chutou muito. Entrou pouco.",
            "Hoje foi difícil fazer gol. Por causa dele.",
            "A trave e ele foram parceiros hoje.",
            "Partida difícil. Saída fácil: defensiva e segura.",
            "Mãos de aço. Reflexo de gato.",
            "A bola que entrava... não entrou.",
        ),
    ),

    PASSE_PRECISAO(
        key = "passe_precisao",
        displayName = "Passe de Precisão",
        defaults = listOf(
            "Hoje a bola tinha endereço.",
            "Distribuiu o jogo com categoria.",
            "Ligou defesa e ataque o jogo inteiro.",
            "Cada passe parecia ensaiado.",
            "Errou pouco e facilitou a vida do time.",
            "O mapa do campo estava na cabeça dele.",
            "A bola saía certeira. Toda vez.",
            "Jogou no modo automático. E funcionou.",
            "Quando a bola chegava nele, ia pro lugar certo.",
            "Fez o simples parecer arte.",
            "Distribuição de alto nível.",
            "Passou a bola como quem passa conhecimento.",
            "Ligou o time inteiro com os pés.",
            "Cada toque, uma jogada. Cada jogada, um acerto.",
            "Visão de jogo impecável.",
            "O time respirou pelo passe dele.",
            "Quem recebia, agradecia.",
            "Fez o jogo andar sem pressa e sem erro.",
        ),
    ),

    PERIGO_EFICIENTE(
        key = "perigo_eficiente",
        displayName = "Perigo Constante (eficiente)",
        defaults = listOf(
            "Quase tudo que chutou entrou.",
            "Transformou chances em gols.",
            "Foi um pesadelo para a defesa.",
            "O goleiro trabalhou, mas não deu conta.",
            "Chutou com classe. Acertou com estilo.",
            "Cada finalização era um aviso. E alguns viraram gol.",
            "Quando chutava, a defesa prendia a respiração.",
            "Hoje o gol estava no pé dele.",
            "Fez valer cada oportunidade.",
            "O goleiro viu de perto. E de baixo também.",
            "Eficiência em forma de jogador.",
            "Mostrou que finalizar bem é arte.",
            "A rede balançou mais de uma vez. Por causa dele.",
            "Chutou certo. Acertou mais ainda.",
        ),
    ),

    PERIGO_VOLUME(
        key = "perigo_volume",
        displayName = "Perigo Constante (volume)",
        defaults = listOf(
            "Se calibrasse o pé, o placar seria outro.",
            "O goleiro trabalhou horas extras.",
            "Tentou até não poder mais.",
            "Chutou de tudo quanto é jeito. O gol resistiu.",
            "Levou perigo constante. Só faltou acertar mais.",
            "A intenção estava lá. A pontaria nem sempre.",
            "Não desistiu nunca. O gol que fugiu.",
            "Finalizou muito. Converteu pouco.",
            "O goleiro agradeceu pelos erros. Foram vários.",
            "Forçou a defesa o jogo inteiro.",
            "Persistência não faltou. Sorte que faltou.",
            "Chutou como se a vida dependesse. A bola não concordou.",
            "Volume alto. Conversão baixa.",
            "O gol estava em greve. Ele insistiu mesmo assim.",
        ),
    ),

    CORREIO(
        key = "correio",
        displayName = "Correio Extraviado",
        defaults = listOf(
            "A correspondência não encontrou o destinatário.",
            "Distribuiu presentes para o adversário.",
            "Hoje o CEP da bola estava errado.",
            "Cada passe era uma aventura.",
            "Tentou inverter o jogo. Inverteu a posse.",
            "A bola foi parar onde não devia.",
            "Fez delivery para o time errado.",
            "Hoje jogou no modo entrega expressa... pro rival.",
            "Os Correios ligaram para pedir dicas.",
            "A bola tinha destino. Só não era o companheiro.",
            "Passou mais bola pro adversário do que pra própria equipe.",
            "A logística dos passes pediu férias.",
            "O GPS da bola recalculou para o outro lado.",
            "Entregou o pacote. No endereço errado.",
            "A bola virou torpedo. Em direção ao inimigo.",
            "Hoje o passe foi surpresa. Inclusive para ele.",
            "A conexão caiu. Várias vezes.",
            "Fez o adversário se sentir em casa com tanta entrega.",
            "A bola saiu. O destino era desconhecido.",
            "Passou a bola como quem passa trote.",
        ),
    ),
}
