"use client";
import { useEffect, useState } from "react";
import { adminRequest } from "@/lib/admin/browser-client";
import { Panel } from "@/components/ui/panel";
type Request = { id:number; clubName:string; requesterName:string; contact:string; status:"PENDING"|"APPROVED"|"REJECTED"; createdAt:string };
type Candidate = { clubId:string; displayName:string; platform:string };
export function TrialRequestsList() {
  const [items,setItems]=useState<Request[]>([]); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState<Record<number,Candidate[]>>({}); const [busy,setBusy]=useState<number|null>(null);
  const load=async()=>{try{setItems(await adminRequest<Request[]>("/api/admin/trial-requests"));}catch{setError("Não foi possível carregar as solicitações.");}};
  useEffect(()=>{void load();},[]);
  async function find(id:number, query:string) { if (!query.trim()) return; try { const candidates = await adminRequest<Candidate[]>(`/api/admin/clubs/search?query=${encodeURIComponent(query)}`); setSearch(p=>({...p,[id]:candidates})); } catch { setError("Não foi possível buscar clubes na EA."); } }
  async function approve(item:Request, club:Candidate) { if (!confirm(`Associar ${item.clubName} ao clube EA ${club.displayName} (${club.clubId}) e iniciar o teste?`)) return; setBusy(item.id); try { await adminRequest(`/api/admin/trial-requests/${item.id}/approve`,{method:"POST",body:JSON.stringify({clubId:club.clubId,displayName:club.displayName,platform:club.platform})}); await load(); } catch { setError("Não foi possível aprovar a solicitação."); } finally { setBusy(null); } }
  async function reject(item:Request) { if(!confirm(`Rejeitar a solicitação de ${item.clubName}?`))return; setBusy(item.id); try{await adminRequest(`/api/admin/trial-requests/${item.id}/reject`,{method:"POST"});await load();}catch{setError("Não foi possível rejeitar a solicitação.");}finally{setBusy(null);} }
  return <section><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[.14em] text-accent">Comercial</p><h1 className="text-2xl font-semibold text-text-primary">Solicitações de teste</h1></div>{error&&<p className="mb-3 text-sm text-loss">{error}</p>}<div className="space-y-3">{items.map(item=><Panel key={item.id}><div className="flex justify-between gap-4"><div><h2 className="font-semibold text-text-primary">{item.clubName}</h2><p className="text-sm text-text-soft">{item.requesterName} · {item.contact}</p><p className="mt-1 text-xs text-muted">{new Date(item.createdAt).toLocaleString("pt-BR")}</p></div><span className="text-xs text-muted">{item.status}</span></div>{item.status==="PENDING"&&<div className="mt-4 space-y-2"><div className="flex gap-2"><input aria-label={`Buscar clube para ${item.clubName}`} className="min-w-0 flex-1 rounded border border-border bg-surface-raised px-3 py-2 text-sm" placeholder="Buscar clube na EA" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void find(item.id,e.currentTarget.value);}}}/><button className="rounded border border-border px-3 text-sm" onClick={e=>{const input=e.currentTarget.previousElementSibling as HTMLInputElement;void find(item.id,input.value)}}>Buscar</button><button disabled={busy===item.id} className="rounded border border-loss/50 px-3 text-sm text-loss" onClick={()=>void reject(item)}>Rejeitar</button></div>{search[item.id]?.map(club=><button key={club.clubId} className="mr-2 rounded bg-accent/10 px-3 py-2 text-sm text-accent" disabled={busy===item.id} onClick={()=>void approve(item,club)}>{club.displayName} · {club.clubId}</button>)}</div>}</Panel>)}</div></section>;
}
